//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENT
    {
        public int commentId { get; set; }
        public string content { get; set; }
        public int memeId { get; set; }
        public System.DateTime createDate { get; set; }
        public int userId { get; set; }
    
        public virtual MEME MEME { get; set; }
    }
}
