//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WELFLEEntities : DbContext
    {
        public WELFLEEntities()
            : base("name=WELFLEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<COMMENT> COMMENTS { get; set; }
        public DbSet<MEME> MEMES { get; set; }
        public DbSet<ROLE> ROLES { get; set; }
        public DbSet<USER> USERS { get; set; }
    }
}
