//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEME
    {
        public MEME()
        {
            this.COMMENTS = new HashSet<COMMENT>();
        }
    
        public int memId { get; set; }
        public string title { get; set; }
        public byte[] picture { get; set; }
        public int note { get; set; }
        public int userId { get; set; }
        public System.DateTime creatDate { get; set; }
    
        public virtual ICollection<COMMENT> COMMENTS { get; set; }
        public virtual USER USER { get; set; }
    }
}
