//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.MEMES = new HashSet<MEME>();
        }
    
        public int userId { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int roleId { get; set; }
    
        public virtual ICollection<MEME> MEMES { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
