//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_Proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANSWERS
    {
        public int answerId { get; set; }
        public string answerContent { get; set; }
        public bool correctAnswer { get; set; }
        public int questionId { get; set; }
    
        public virtual QUESTIONS QUESTIONS { get; set; }
    }
}
