//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_Proj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUIZEntitiesData : DbContext
    {
        public QUIZEntitiesData()
            : base("name=QUIZEntitiesData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANSWERS> ANSWERS { get; set; }
        public virtual DbSet<QUESTIONS> QUESTIONS { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<SCORES> SCORES { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
